### ISSUE TITLE
No sub messages are shown for suggested requests

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#22]
The most likely reason is, that loading a stored conversation throws an 404.

For some reason a exception is thrown when loading a conversation .

Exception while invoking method 'redlink:getStoredConversation' Error: failed [404] <html> <head>   <title>We're sorry - something went completely wrong!</title> </head> <body> <h1>Ooops, something went wrong here.</h1> <p>We're sooooo sorry... <strong>:-(</strong>.</p> </body> </html>
  at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
  at Object.<anonymous> (packages/meteor.js:213:24)
  at Object.HTTP.call (packages/rocketchat_monitoring.js:3454:33)
  at Object.HTTP.get (/opt/Rocket.Chat/programs/server/packages/http.js:74:20)
  at RedlinkAdapter.getStoredConversation (/opt/Rocket.Chat/programs/server/packages/dbs_ai.js:633:24)
  at [object Object].Meteor.methods.redlink:getStoredConversation (/opt/Rocket.Chat/programs/server/packages/dbs_ai.js:53:19)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1069:26)
  at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
  at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:755:85

    - - - - -
  at makeErrorByStatus (/opt/Rocket.Chat/programs/server/packages/http.js:40:10)
  at Request._callback (/opt/Rocket.Chat/programs/server/packages/http.js:220:47)
  at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:200:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1067:10)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:988:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:921:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickDomainCallback (node.js:397:17)

**Comment by ruKurz** [comment]
Since the smarti release will come soon, that covers a completely new UI of the knowledge base, we won't fix this issue.
